# PHP CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-php/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/php:7.3.8
      - image: circleci/mysql:8.0.17
      - image: circleci/redis:5.0
    working_directory: ~/laravel-base

    steps:
      - checkout
      - run: composer global require "squizlabs/php_codesniffer=*"
      - run: git clone https://github.com/wataridori/framgia-php-codesniffer.git ~/.composer/vendor/squizlabs/php_codesniffer/src/Standards/Framgia

      # Download and cache dependencies
      - restore_cache:
          keys:
            # "composer.lock" can be used if it is committed to the repo
            - v1-dependencies-{{ checksum "composer.json" }}

            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      # Disable php memory limit
      - run: echo 'memory_limit=-1' | sudo tee -a /usr/local/etc/php/php.ini

      # Composer install
      - run: composer install -n --prefer-dist

      # run tests!
      - run: sudo ~/.composer/vendor/bin/phpcs --standard=Framgia app
      - run: php -r "file_exists('.env') || copy('.env.example', '.env');"
      - run: php artisan key:generate
      # - run: vendor/bin/phpunit
